### ISSUE TITLE
Failed to install on Ubuntu

### ISSUE THREAD

**Issue by NielsKSchjoedt** [ankane/AnomalyDetection.rb#3]
```
gem install anomaly_detection

Fetching anomaly_detection-0.1.4.gem
Building native extensions. This could take a while...
ERROR:  Error installing anomaly_detection:
	ERROR: Failed to build gem native extension.

    current directory: /home/semaphore/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/anomaly_detection-0.1.4/ext/anomaly_detection
/home/semaphore/.rbenv/versions/2.7.6/bin/ruby -I /home/semaphore/.rbenv/versions/2.7.6/lib/ruby/site_ruby/2.7.0 -r ./siteconf20221114-4203-1r3ghch.rb extconf.rb
checking for rice/rice.hpp in /home/semaphore/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rice-4.0.4/include... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/semaphore/.rbenv/versions/2.7.6/bin/$(RUBY_BASE_NAME)
/home/semaphore/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rice-4.0.4/lib/mkmf-rice.rb:120:in `<top (required)>': Could not find rice/rice.hpp header (RuntimeError)
	from /home/semaphore/.rbenv/versions/2.7.6/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160:in `require'
	from /home/semaphore/.rbenv/versions/2.7.6/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160:in `rescue in require'
	from /home/semaphore/.rbenv/versions/2.7.6/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:149:in `require'
	from extconf.rb:1:in `<main>'
/home/semaphore/.rbenv/versions/2.7.6/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require': cannot load such file -- mkmf-rice (LoadError)
	from /home/semaphore/.rbenv/versions/2.7.6/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from extconf.rb:1:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/semaphore/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/anomaly_detection-0.1.4/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/semaphore/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/anomaly_detection-0.1.4 for inspection.
Results logged to /home/semaphore/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/anomaly_detection-0.1.4/gem_make.out
```

Looks to be the same as: https://github.com/ankane/field_test/issues/33

```
lsb_release -a

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
```

**Comment by hampld** [comment]
It looks like we were able to resolve the issue. on ubuntu 18.04 rice did not have the required gcc version (c++17). upgrading to ubuntu 20.04 did the trick. the issue can be closed.

**Comment by ankane** [comment]
GCC 7 (the version installed with `build-essential` on Ubuntu 18.04) should support it, but glad you found something that works.

https://github.com/ankane/AnomalyDetection.rb/actions/runs/3472475871/jobs/5803352597

**Comment by brusacco** [comment]
On Centos:

sudo yum update
sudo yum groupinstall "Development Tools"
sudo yum install centos-release-scl
sudo yum install devtoolset-8-toolchain

scl enable devtoolset-8 bash

After completing these steps, you should have C++17 support available on your CentOS system. You can compile and run C++17 code using the installed GCC version.

Note: When using the devtoolset-8 environment, you need to enable it in each new shell session or update your shell configuration to set it as the default environment.
