### ISSUE TITLE
Issue with rake assets:precompile

### ISSUE THREAD

**Issue by breiko83** [ankane/AnomalyDetection.rb#4]
```
 => ERROR [10/11] RUN rake assets:precompile                                                                                                                                                         2.9s 
------                                                                                                                                                                                                    
 > [10/11] RUN rake assets:precompile:                                                                                                                                                                    
#0 2.770 rake aborted!                                                                                                                                                                                    
#0 2.770 LoadError: /usr/local/bundle/gems/anomaly_detection-0.2.2/lib/anomaly_detection/ext.so: undefined symbol: _ZTINSt10filesystem7__cxx1116filesystem_errorE - /usr/local/bundle/gems/anomaly_detection-0.2.2/lib/anomaly_detection/ext.so                                                                                                                                                                     
#0 2.770 /usr/local/bundle/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'                                                                                   
#0 2.770 /usr/local/bundle/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
#0 2.770 /usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/dependencies.rb:332:in `block in require'
#0 2.770 /usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/dependencies.rb:299:in `load_dependency'
#0 2.770 /usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/dependencies.rb:332:in `require'
#0 2.770 /usr/local/bundle/gems/anomaly_detection-0.2.2/lib/anomaly_detection.rb:2:in `<main>'
#0 2.770 /usr/local/bundle/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
#0 2.770 /usr/local/bundle/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
#0 2.770 /usr/local/bundle/gems/bundler-2.3.19/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
#0 2.770 /usr/local/bundle/gems/bundler-2.3.19/lib/bundler/runtime.rb:55:in `each'
#0 2.770 /usr/local/bundle/gems/bundler-2.3.19/lib/bundler/runtime.rb:55:in `block in require'
#0 2.770 /usr/local/bundle/gems/bundler-2.3.19/lib/bundler/runtime.rb:44:in `each'
#0 2.770 /usr/local/bundle/gems/bundler-2.3.19/lib/bundler/runtime.rb:44:in `require'
#0 2.770 /usr/local/bundle/gems/bundler-2.3.19/lib/bundler.rb:188:in `require'
#0 2.770 /app/config/application.rb:6:in `<top (required)>'
#0 2.770 /app/Rakefile:4:in `require_relative'
#0 2.770 /app/Rakefile:4:in `<top (required)>'
#0 2.770 /usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
#0 2.770 (See full trace by running task with --trace)
------
failed to solve: process "/bin/sh -c rake assets:precompile" did not complete successfully: exit code: 1
```

**Comment by ankane** [comment]
Hi @breiko83, which Docker image and Ruby version are you using?

**Comment by breiko83** [comment]
I'm using ruby:3.0.6-slim-buster but I tried with 3.1 and 3.2 too. They all use gcc-8 and give the same error.
I found [this](https://github.com/xuanyan0x7c7/insertionfinder/issues/1) issue on a different library. Maybe could be a clue?

**Comment by breiko83** [comment]
I tried replacing 
`$CXXFLAGS += " -std=c++17 $(optflags)"`
with:
`$CXXFLAGS += " -lstdc++fs $(optflags)"`
but no luck

**Comment by breiko83** [comment]
No luck. Curiously I remove anomaly_detection and it now fails with breakout-detection. Same error:

```
#14 [10/12] RUN echo $(gcc --version)
#14 0.284 gcc (Debian 8.3.0-6) 8.3.0 Copyright (C) 2018 Free Software Foundation, Inc. This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#14 DONE 0.3s

#15 [11/12] RUN rake assets:precompile
#15 2.922 rake aborted!
#15 2.922 LoadError: /usr/local/bundle/gems/breakout-detection-0.2.0/lib/breakout/ext.so: undefined symbol: _ZTINSt10filesystem7__cxx1116filesystem_errorE - /usr/local/bundle/gems/breakout-detection-0.2.0/lib/breakout/ext.so
#15 2.922 /usr/local/bundle/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
#15 2.922 /usr/local/bundle/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
#15 2.922 /usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/dependencies.rb:332:in `block in require'
#15 2.922 /usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/dependencies.rb:299:in `load_dependency'
#15 2.922 /usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/dependencies.rb:332:in `require'
#15 2.922 /usr/local/bundle/gems/breakout-detection-0.2.0/lib/breakout.rb:2:in `<main>'
#15 2.922 /usr/local/bundle/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
#15 2.922 /usr/local/bundle/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
#15 2.922 /usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/dependencies.rb:332:in `block in require'
#15 2.922 /usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/dependencies.rb:299:in `load_dependency'
#15 2.922 /usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/dependencies.rb:332:in `require'
#15 2.922 /usr/local/bundle/gems/breakout-detection-0.2.0/lib/breakout-detection.rb:1:in `<main>'
#15 2.922 /usr/local/bundle/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
#15 2.922 /usr/local/bundle/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
#15 2.922 /usr/local/bundle/gems/bundler-2.3.19/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
#15 2.922 /usr/local/bundle/gems/bundler-2.3.19/lib/bundler/runtime.rb:55:in `each'
#15 2.922 /usr/local/bundle/gems/bundler-2.3.19/lib/bundler/runtime.rb:55:in `block in require'
#15 2.922 /usr/local/bundle/gems/bundler-2.3.19/lib/bundler/runtime.rb:44:in `each'
#15 2.922 /usr/local/bundle/gems/bundler-2.3.19/lib/bundler/runtime.rb:44:in `require'
#15 2.922 /usr/local/bundle/gems/bundler-2.3.19/lib/bundler.rb:188:in `require'
#15 2.922 /app/config/application.rb:6:in `<top (required)>'
#15 2.922 /app/Rakefile:4:in `require_relative'
#15 2.922 /app/Rakefile:4:in `<top (required)>'
#15 2.922 /usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
#15 2.922 (See full trace by running task with --trace)
#15 ERROR: process "/bin/sh -c rake assets:precompile" did not complete successfully: exit code: 1
```

**Comment by ankane** [comment]
Thanks for checking. Both gems use Rice (which uses `std::filesystem::filesystem_error` referenced in the error message), so that's likely where the issue is. Since Buster is EOL and it works on Bullseye, changing the image might be the easiest fix.
